" Minimal Vim config for basic usage
set encoding=utf-8
scriptencoding utf-8

if has('vim_starting')
  set nocompatible
endif

" Plugin setup (optional if vim-plug exists)
let s:plug_path = expand('~/.vim/autoload/plug.vim')
if filereadable(s:plug_path)
  call plug#begin(expand('~/.vim/plugged'))

  Plug 'vim-airline/vim-airline'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-sleuth'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'dracula/vim'

  call plug#end()
endif

" Core behavior
filetype plugin indent on
syntax enable

set number
set cursorline
set splitbelow
set splitright
set hidden
set autoread
set mouse=a
set wildmenu
set ruler
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch

" Indentation
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2

" Persistent undo (safer than disabling all recovery files)
set undofile
set undodir=~/.vim/undo
if !isdirectory(&undodir) | call mkdir(&undodir, 'p') | endif
" fzf runtime path (Apple Silicon + Intel Homebrew)
if isdirectory('/opt/homebrew/opt/fzf')
  set rtp+=/opt/homebrew/opt/fzf
elseif isdirectory('/usr/local/opt/fzf')
  set rtp+=/usr/local/opt/fzf
endif

" Theme
silent! colorscheme dracula

" Leader and mappings
let mapleader = ','
let g:mapleader = ','

nnoremap <leader>w :write<CR>
nnoremap <silent> <leader><CR> :nohlsearch<CR>
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l

if exists(':Files')
  nnoremap <leader>ff :Files<CR>
endif

if exists(':GFiles')
  nnoremap <leader>fg :GFiles<CR>
endif

" Trim trailing whitespace on common text/code files
augroup user_trim_whitespace
  autocmd!
  autocmd BufWritePre *.py,*.js,*.ts,*.tsx,*.go,*.tf,*.yaml,*.yml,*.md :%s/\s\+$//e
augroup END
